---
- name: Install Dependencies
  apt:
    name: golang-go
    state: present
    update_cache: true
  become: yes

- name: Install powerline-go
  command: /usr/bin/go get -u github.com/justjanne/powerline-go
  environment:
    GO_PATH: $HOME/go
  args:
    creates: go/bin/powerline-go

