---
- name: Install Go Dependencies (apt)
  apt:
    name: golang-go
    state: present
    update_cache: true
  become: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install Go Dependencies (homebrew)
  homebrew:
    name: golang
    state: present
  when: ansible_facts['os_family'] == "Darwin"
 
- name: Download powerline-go sources
  git:
    repo: https://github.com/justjanne/powerline-go.git
    dest: "{{ ansible_env.HOME }}/go/src/github.com/justjanne/powerline-go"
    version: main
    force: true

- name: Patch powerline-go duration module for fish shell
  patch:
    src: segment-duration.go.patch
    dest: "{{ ansible_env.HOME }}/go/src/github.com/justjanne/powerline-go/segment-duration.go"
  when: powerline_go.fish_duration_patch is defined and powerline_go.fish_duration_patch == True
  tags: install

- name: Build powerline-go
  command: go install
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
  args:
    chdir: "{{ ansible_env.HOME }}/go/src/github.com/justjanne/powerline-go"
    creates: "{{ ansible_env.HOME }}/go/bin/powerline-go"
  tags: install

- block:
  - name: Check if fish script path exists
    stat:
      path: "{{ fish_shell_script_path | dirname }}"
    register: path_details
  - name: Create fish script path
    file:
      path: "{{ fish_shell_script_path | dirname }}"
      state: directory
      mode: 0755
    when: path_details.stat.exists == false
  - name: Install powerline-go fish shell support
    template:
      src: powerline-go.fish.j2
      dest: "{{ fish_shell_script_path }}"
    tags: configure
  when: powerline_go.install_fish is defined and powerline_go.install_fish == True

- block:
  - name: Check if zsh script path exists
    stat:
      path: "{{ zsh_shell_script_path | dirname }}"
    register: path_details
  - name: Create zsh script path
    file:
      path: "{{ zsh_shell_script_path | dirname }}"
      state: directory
      mode: 0755
    when: path_details.stat.exists == false
  - name: Install powerline-go zsh support
    template:
      src: powerline-go.zsh.j2
      dest: "{{ zsh_shell_script_path }}"
    tags: configure
  when: powerline_go.install_zsh is defined and powerline_go.install_zsh == True


