---
- name: load source vars
  with_first_found:
    - '../vars/architecture/{{ ansible_architecture | lower }}.yml'
    - ../vars/architecture/default.yml
  include_vars: '{{ item }}'

- name: load sha256sums
  with_first_found:
    - '../vars/versions/powerline-go-{{ ansible_system | lower }}-{{ powerline_go_arch }}.{{ powerline_go_version}}.yml'
    - '../vars/versions/default.yml'
  include_vars: '{{ item }}'

- name: Download and install powerline-go binary
  get_url: 
    url: "https://github.com/justjanne/powerline-go/releases/download/{{ powerline_go_version }}/powerline-go-{{ ansible_system | lower}}-{{ powerline_go_arch}}"
    dest: "{{ ansible_env.HOME }}/go/bin/powerline-go"
    checksum: 'sha256:{{ powerline_go_sha256_sum }}'

- block:
  - name: Check if fish script path exists
    stat:
      path: "{{ fish_shell_script_path | dirname }}"
    register: path_details
  - name: Create fish script path
    file:
      path: "{{ fish_shell_script_path | dirname }}"
      state: directory
      mode: 0755
    when: path_details.stat.exists == false
  - name: Install powerline-go fish shell support
    template:
      src: powerline-go.fish.j2
      dest: "{{ fish_shell_script_path }}"
    tags: configure
  when: powerline_go.install_fish is defined and powerline_go.install_fish == True

- block:
  - name: Check if zsh script path exists
    stat:
      path: "{{ zsh_shell_script_path | dirname }}"
    register: path_details
  - name: Create zsh script path
    file:
      path: "{{ zsh_shell_script_path | dirname }}"
      state: directory
      mode: 0755
    when: path_details.stat.exists == false
  - name: Install powerline-go zsh support
    template:
      src: powerline-go.zsh.j2
      dest: "{{ zsh_shell_script_path }}"
    tags: configure
  when: powerline_go.install_zsh is defined and powerline_go.install_zsh == True


